export const config: IConfig = {
  name: import.meta.env.VITE_APP_TITLE,
  schemeLink: import.meta.env.VITE_APP_SCHEME_LINK,
  downloadLink: import.meta.env.VITE_APP_DOWNLOAD_LINK,
  shareLink: import.meta.env.VITE_APP_SHARE_LINK,
  appid: import.meta.env.VITE_APP_ID,
  aMapKey: import.meta.env.VITE_A_MAP_KEY,
  scanAuthNavigation: import.meta.env.VITE_SCAN_AUTH_NAVIGATION,
  iosAppId: import.meta.env.VITE_IOS_APP_ID,
  logo: import.meta.env.VITE_LOGO,
  customerServiceMobile: import.meta.env.VITE_CUSTOMER_SERVICE_MOBILE,
  customerServiceEmail: import.meta.env.VITE_CUSTOMER_SERVICE_EMAIL,
  imWebSrc: import.meta.env.VITE_IM_WEB_SRC,
  baseWsUrl: import.meta.env.VITE_BASE_WS_URL,
  enableGetClipboard: import.meta.env.VITE_ENABLE_GET_CLIPBOARD,
  enableMiniBarStartUpApp: import.meta.env.VITE_ENABLE_MINI_BAR_START_UP_APP,
  mainColor: import.meta.env.VITE_MAIN_COLOR,
  lightColor: import.meta.env.VITE_LIGHT_COLOR,
  aiderLightColor: import.meta.env.VITE_AIDER_LIGHT_COLOR,
  defaultUserPhoto: import.meta.env.VITE_DEFAULT_USER_PHOTO,
  enableFetchMobileLogin: import.meta.env.VITE_ENABLE_FETCH_MOBILE_LOGIN,
}
