/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/auth/login" |
       "/pages/category/category" |
       "/pages/error/404" |
       "/pages/message/message" |
       "/pages/public/search" |
       "/pages/user/user" |
       "/pages/auth/method/html5Login" |
       "/pages/auth/method/wechatH5Login" |
       "/pages/auth/method/wechatMPLogin" |
       "/pages/user/coupon/coupon" |
       "/pages/user/coupon/detail" |
       "/pages/user/setting/about" |
       "/pages/user/setting/feedback" |
       "/pages/user/setting/i18n" |
       "/pages/user/setting/personal" |
       "/pages/user/setting/security" |
       "/pages/user/tool/mission" |
       "/pages/user/tool/point" |
       "/pages/user/tool/setting" |
       "/pages/user/tool/signIn" |
       "/pages/user/tool/test" |
       "/pages/user/tool/tool";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/category/category" | "/pages/message/message" | "/pages/user/user"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
